name: Sync Files to New Repository

on:
  push:
    paths:
      - 'dashboards/full_healthcare_demo.dashboard.lookml'
      - 'dashboards/mini_healthcare_demo.dashboard.lookml'
      - 'explores/fct_claims.explore.lkml'
      - 'explores/fct_hospital_events.explore.lkml'
      - 'explores/fct_patient_conditions.explore.lkml'
      - 'views/derived/dt_hospital_readmissions.view.lkml'
      - 'views/raw/dim_organizations.view.lkml'
      
  workflow_dispatch: # Enable manual trigger

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: mkryed/testwithcecile # Replace with the source repository

      - name: Retrieve Latest Commit Message
        id: commit_message
        run: |
          cd $GITHUB_WORKSPACE
          latest_commit_message=$(git log -1 --pretty=%B)  # Retrieves the latest commit message
          echo "::set-output name=message::${latest_commit_message}"  # Sets the commit message as an output

      - name: Sync Files to Target Repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Clone the target repository
          git clone https://mkryed:${{ secrets.TARGET }}@github.com/mkryed/test_sync_external_files temp
          cd temp
          
          for file in 'dashboards/full_healthcare_demo.dashboard.lookml' \
                      'dashboards/mini_healthcare_demo.dashboard.lookml' \
                      'explores/fct_claims.explore.lkml' \
                      'explores/fct_hospital_events.explore.lkml' \
                      'explores/fct_patient_conditions.explore.lkml' \
                      'views/derived/dt_hospital_readmissions.view.lkml' \
                      'views/raw/dim_organizations.view.lkml'
          do
            cp $file .
          done

          # Commit and push changes to the target repository
          new_message="${{ steps.commit_message.outputs.message }}"
          git add .
          git commit -m "${new_message}"
          git push origin main  # Replace 'main' with your target branch
