name: Sync Files to New Repository

on:
  push:
    paths:
      - 'views/raw/fct_claims.view.lkml'
      - 'views/raw/fct_hospital_events.view.lkml'
      - 'views/raw/dim_organizations.view.lkml'

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: mkryed/testwithcecile

      - name: Sync Files to New Repository
        run: |
          cd $GITHUB_WORKSPACE
          mkdir temp_source

          IFS=$'\n' # Set the Internal Field Separator to new line
          for file_path in $(git diff --name-only HEAD^ HEAD); do
            file_dir=$(dirname "$file_path")
            file_name=$(basename "$file_path")
            
            # Create the same directory structure in temp_source
            mkdir -p "temp_source/$file_dir"

            # Copy the changed file and its directory structure to temp_source
            cp "$file_path" "temp_source/$file_dir"
          done            


          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://mkryed:${{ secrets.TARGET }}@github.com/mkryed/test_sync_2 temp_target

          # Copy changed files to temp_target
          cd temp_source
          rsync -av --delete --exclude='.git' temp_source/ temp_target/

          # Commit and push changes to the target repository
          cd temp_target
          git add .
          git commit -m "Sync changes from source repository"
          git push origin main # Replace 'main' with your target branch
