name: Sync .lkml Files

on:
  push:
    branches:
      - master  # Change to the branch you want to trigger the sync on

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: mkryed/testwithcecile  # Replace with the source repository URL

      - name: Filter .lkml Files with "external"
        run: |
          mkdir filtered_files
          find . -type f -name '*.lkml' -exec grep -l "external" {} + | xargs -I{} cp {} filtered_files/
          echo "FILTERED_FOLDERS=$(find . -type f -name '*.lkml' -exec dirname {} \; | sort | uniq)" >> $GITHUB_ENV


      - name: Clone Target Repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://mkryed:${{ secrets.TARGET }}@github.com/mkryed/test_sync_external_files target_repository

      # - name: Copy Filtered Files to Target Repository
      #   run: |
      #     find filtered_files -type f -name '*.lkml' -exec sh -c 'mkdir -p target_repository/$(dirname "{}") && cp "{}" target_repository/$(dirname "{}")/' \;

      - name: Create Folder Structure in Target Repository
        run: |
          IFS=$'\n' read -rd '' -a folders <<< "${{ steps.filter_lkml.outputs.filtered_folders }}"
          for folder in "${folders[@]}"; do
            mkdir -p target_repository/"$folder"
          done

      

      # - name: mkryed/test_sync_external_files PRIVATE repository
      #   uses: actions/clone-github-repo-action@v2.1
      #   with:
      #     owner: 'mkryed'
      #     repository: 'test_sync_external_files'
      #     access-token: ${{ secrets.TARGET }}

      # - name: Copy Filtered Files to Target Repository
      #   run: cp -R filtered_files/. target_repository/

      - name: Commit and Push to Target Repository
        working-directory: target_repository
        run: |
          git add .
          git commit -m "Sync .lkml files containing 'external'"
          git push origin main  # Replace with the target branch if needed
