name: Sync Files to New Repository

on:
  push:
    paths:
      - 'views/raw/fct_claims.view.lkml'

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: mkryed/testwithcecile

      - name: Sync Files to New Repository
        run: |
          cd $GITHUB_WORKSPACE
          mkdir temp_source

          # Copy specified files and directories from source repository to temp_source
          cp views/raw/fct_claims.view.lkml temp_source/

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://mkryed:${{ secrets.TARGET }}@github.com/mkryed/test_sync_2 temp_target

          # Copy changed files to temp_target
          cd temp_source
          rsync -av --delete --exclude='.git' ./ ../temp_target/

          # Commit and push changes to the target repository
          cd ../temp_target
          git add .
          git commit -m "Sync changes from source repository"
          git push origin main # Replace 'main' with your target branch
