name: Init Copy Files with "TAG" to Another Repository

on:
  push:
    branches:
      - master

jobs:
  copy_lkml:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: mkryed/testwithcecile
          
      - name: Check for Changes and get latest commit
        working-directory: mkryed/testwithcecile
        run: |
          latest_commit_message=$(git log -1 --pretty=%B)

      - name: Find Files with TAG
        id: find_files
        run: |
          files=$(grep --exclude-dir=".github" -rl "external" .)
          if [ -n "$files" ]; then
            mkdir -p target_repository
            echo "$files" | xargs -I{} sh -c 'mkdir -p target_repository/$(dirname "{}") && cp "{}" target_repository/$(dirname "{}")/'
          else
            echo "No files with 'external' found."
            echo "::set-output name=files_not_found::true"
          fi

      - name: Clone Target Repository as repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://mkryed:${{ secrets.TARGET }}@github.com/mkryed/test_sync_external_files repository

      - name: Copy Files to Target Repository
        run: cp -r target_repository/. repository/

      - name: Check for Changes then Commit and Push to Target Repository
        working-directory: repository
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected. Committing and pushing..."
            git add .
            git commit -m "$latest_commit_message"
            git push origin main
          else
            echo "No changes to commit."
          fi

