name: Copy .lkml Files to Another Repository

on:
  push:
    branches:
      - master

jobs:
  copy_lkml:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: mkryed/testwithcecile

      - name: Perform Git Status
        id: git_status
        run: |
          # Capture the status and set to 'null' to prevent script failure
          git_status=$(git status)
          if [ "$git_status" = "On branch main
          Your branch is up to date with 'origin/main'.

          nothing to commit, working tree clean" ]; then
            echo "::set-output name=git_status::null"
          fi

      - name: Find .lkml Files with "external"
        if: steps.git_status.outputs.git_status != 'null'
        id: find_files
        run: |
          files=$(grep --exclude-dir=".github" -rl "external" .)
          if [ -n "$files" ]; then
            mkdir -p target_repository
            echo "$files" | xargs -I{} sh -c 'mkdir -p target_repository/$(dirname "{}") && cp "{}" target_repository/$(dirname "{}")/'
          else
            echo "No files with 'external' found."
          fi

        # COPY only files that contain external
      # - name: Find and Copy .lkml Files with "external"
      #   run: |
      #     find . -type f -name '*.lkml' -exec grep -l "external" {} + | xargs -I{} sh -c 'mkdir -p target_repository/$(dirname "{}") && cp "{}" target_repository/$(dirname "{}")/'


      - name: Clone Target Repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://mkryed:${{ secrets.TARGET }}@github.com/mkryed/test_sync_external_files repository

      - name: Copy Filtered Files to Target Repository
        run: cp -r target_repository/. repository/
      
        
      - name: Commit and Push to Target Repository
        working-directory: repository
        run: |
          git add .
          git commit -m "Sync .lkml files containing 'external'"
          git push origin main  # Replace with the target branch if needed
