name: Copy .lkml Files to Another Repository

on:
  push:
    branches:
      - master

jobs:
  copy_lkml:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: mkryed/testwithcecile

      - name: Find and Copy .lkml Files
        run: |
          find . -type f -name '*.lkml' -exec sh -c 'mkdir -p target_repository/$(dirname "{}") && cp "{}" target/{}' \;

      - name: Clone Target Repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://mkryed:${{ secrets.TARGET }}@github.com/mkryed/test_sync_external_files repository

      - name: Copy Filtered Files to Target Repository
        run: cp -r target/. repository/
        
      - name: Commit and Push to Target Repository
        working-directory: repository
        run: |
          git add .
          git commit -m "Sync .lkml files containing 'external'"
          git push origin main  # Replace with the target branch if needed
